defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- hardware: slurm
- graph: stretched_grid
- model: graphtransformer
- training: default
- override hydra/hydra_logging: disabled  
- override hydra/job_logging: disabled 
- _self_

hydra:  
  output_subdir: null  
  run:  
    dir: .


dataloader:
  dataset:
    cutout:
      - dataset: ${hardware.paths.data}/MEPS/${hardware.files.dataset_lam}
      - dataset: ${hardware.paths.data}/ERA5/${hardware.files.dataset}
    adjust: all

  training:
    start: 2023-01-01
    end: 2023-01-05
  validation:
    start: 2023-02-01
    end: 2023-02-05
  test:
    start: 2023-02-10
    end: 2023-02-15

hardware:
  paths:
    data: /pfs/lustrep4/scratch/project_465001383/aifs/dataset/
    output: /pfs/lustrep4//scratch/project_465001383/aifs/experiments/test-anemoi-training-2/
    graph: ${hardware.paths.output}
  files:
    dataset: aifs-od-an-oper-0001-mars-o96-2016-2023-6h-v6.zarr
    dataset_lam: aifs-meps-10km-2020-2024-6h-v6.zarr
    graph: test_aw_rescale.pt

data:
  resolution: None
  forcing:
  - "cos_latitude"
  - "cos_longitude"
  - "sin_latitude"
  - "sin_longitude"
  - "cos_julian_day"
  - "cos_local_time"
  - "sin_julian_day"
  - "sin_local_time"
  - "insolation"
  - "lsm"
  - "z"

  diagnostic:
  - tp

  normalizer:
    max: 
    - "z"

diagnostics:
  log:
    mlflow:
      enabled: False
 
training:
  node_loss_weights:
    _target_: anemoi.training.losses.nodeweights.ReweightedGraphNodeAttribute
    target_nodes: ${graph.data}
    node_attribute: area_weight
    scaled_attribute: cutout
    weight_frac_of_total: 0.5